# Generated by Django 4.0.3 on 2022-04-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('img', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('family', models.CharField(choices=[('Fr', 'Fringillidae'), ('Es', 'Estrildidae'), ('Pl', 'Ploceidae'), ('Pa', 'Passeridae')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
