# Generated by Django 4.0.3 on 2022-04-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_finch_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('size', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
    ]
