# Generated by Django 4.0.3 on 2022-04-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_birdhouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdhouse',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=10),
        ),
    ]
