# Generated by Django 4.0.3 on 2022-04-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_birdhouse_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='birdhouses',
            field=models.ManyToManyField(to='main_app.birdhouse'),
        ),
    ]
